#!/bin/sh

# Copy dotfiles from dot/
for item in $(find dot ! -ipath '**/.*'); do
target=~/`echo $item | sed -e 's@dot/*@.bash/@'`

  if [ -d $item ]; then
test -d $target || mkdir -p $target
  elif [ -f $item ]; then
echo "Copying ${item} to ${target}"
    cp $item $target
  fi
done
