# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Pure
ZSH_THEME=""

plugins=(
git
)

source $ZSH/oh-my-zsh.sh

autoload -U promptinit; promptinit
prompt pure

alias zshconfig="code ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"
alias gcah="git commit --amend --reset-author -C head"